[theme]
base = "light"
backgroundColor = "#BFDDF0"
secondaryBackgroundColor = "#8CC0EB"
textColor = "#0C2336"
primaryColor = "#8CC0EB"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

