[theme]
base = "light"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FAFAFA"
textColor = "#0F0F0F"
primaryColor = "#007979"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
