[theme]
base = "dark"
backgroundColor = "#0D0E11"
secondaryBackgroundColor = "#141519"
textColor = "#F0F0F5"
primaryColor = "#6C63FF"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
